name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Test with Maven
      run: mvn test
      
    - name: Notify Jenkins to deploy
      if: success() && github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        curl -X POST http://VOTRE_SERVEUR_JENKINS:8080/job/stock-api-deploy/build \
          --user ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }} \
          --data-urlencode "token=${{ secrets.JENKINS_JOB_TOKEN }}"
